import type { Article } from "@/lib/content";

const chapters = [
`## Define the commercial decision before the deliverable

Strong work begins by naming the decision a customer must make and the business change that decision should create. A page, campaign or content programme is only the delivery format. Start with the audience, the situation that brought them to the business, the alternative they are considering and the evidence they need before moving forward. Interview sales and customer-facing teams, review real enquiries and compare what customers ask with what the current experience explains. Turn that evidence into a short decision statement. It should identify the audience, desired action, principal hesitation and proof required. This prevents subjective debates about design or volume from replacing the actual problem. It also creates a practical test for every section: does this information help the right person understand, trust or act?`,

`## Research language, intent and context together

Keyword data is useful, but it is not a complete picture of intent. Two people can use the same phrase while needing very different answers. Combine search demand with sales-call language, support questions, proposal objections, on-site searches and competitor patterns. Group findings by the decision stage: learning, comparing, validating or acting. Record the exact language customers use, but also document the context behind it. A founder researching a redesign may be worried about lost rankings, while a marketing lead may be worried about internal publishing delays. Those concerns deserve different proof and next steps. The resulting research should guide navigation, page hierarchy, headings, examples and internal links, not sit unused in a spreadsheet after the initial workshop.`,

`## Build an information hierarchy people can predict

People should not need to learn a company’s internal vocabulary before finding an answer. Organise the experience around recognisable customer needs and distinct services. Give each important intent one clear primary destination, then connect supporting articles, proof and resources around it. Avoid several pages competing for the same purpose. Before writing, create a page map that states the audience, question, primary action and supporting evidence for every URL. Review the map for gaps, overlaps and orphaned pages. A predictable hierarchy helps visitors recover when they land deep within the site, gives search systems cleaner topical relationships and makes future publishing easier. Navigation labels should be concrete enough that a first-time visitor can anticipate what will appear after clicking.`,

`## Lead with an answer, then earn attention with depth

The opening should resolve the central question quickly without pretending the subject is simpler than it is. State the most useful answer, qualify it where necessary and explain what the reader should consider next. Depth belongs underneath that orientation. Use descriptive headings that still make sense when scanned on their own. Break complex decisions into criteria, processes, examples, risks and next actions. Short answer passages help both readers and answer systems, while the fuller explanation builds confidence. Do not bury the answer behind a long brand introduction. Equally, do not stretch a thin answer across thousands of words. Every section should add a decision, distinction, method, example or piece of evidence the reader could not get from the headline alone.`,

`## Make positioning specific enough to exclude

Effective positioning is not a list of every capability. It explains who the work is for, which high-value problem it solves, what approach makes the solution credible and why the choice matters now. Specificity will make some visitors realise the offer is not for them, which is useful. A focused message improves lead quality and gives content a coherent centre. Test positioning against real alternatives, including doing nothing, hiring internally and choosing a cheaper generalist. Replace unsupported superlatives with meaningful distinctions such as process, expertise, operating model, sector knowledge or ownership. Then carry the same core promise through the homepage, service pages, cases, articles and contact journey while adapting the detail to each page’s purpose.`,

`## Use proof where doubt appears

Proof is most persuasive when it sits beside the claim it supports. If a page promises a clearer buying journey, show the reasoning, artefact or outcome that demonstrates it. Useful proof can include approved case evidence, relevant work, process detail, named expertise, customer language, original research and transparent limitations. Avoid vague testimonial carousels disconnected from the service being considered. For every major claim, ask what a thoughtful buyer would need to verify it. Where numeric results are used, explain the baseline, period, method and other factors that may have influenced the outcome. Where results cannot be shared, demonstrate competence through a clear framework and honest trade-offs rather than inventing certainty. Credibility grows when the business distinguishes evidence, experience and opinion.`,

`## Design the page around a sequence of decisions

A high-performing page is not a collection of attractive sections. It is a sequence that moves from orientation to relevance, understanding, confidence and action. The opening establishes audience and outcome. The middle explains the approach, differentiators and proof. Later sections answer objections and make the next step feel proportionate. The sequence can vary with intent: an urgent visitor may need contact information immediately, while a comparison visitor may need detailed methodology first. Provide a clear primary action throughout without turning every paragraph into a sales pitch. Secondary links should help readers continue evaluating rather than send them into unrelated content. On mobile, repeat the same logical sequence and check that cards, accordions and buttons do not hide essential information or create unnecessary effort.`,

`## Treat accessibility and performance as persuasion

Speed, readability and accessibility directly affect trust. Compress images, reserve their dimensions and load only what the current view needs. Use semantic headings, meaningful link text, keyboard-accessible controls, sufficient contrast and visible focus states. Write alternative text when an image communicates information, and leave it empty when the image is purely decorative. Test real pages on ordinary mobile connections, not only a powerful laptop. Remove scripts and effects that add weight without helping the decision. Motion should support orientation and respect reduced-motion preferences. A technically polished experience communicates operational care before the visitor reads a case study. It also widens the audience that can use the site and reduces the friction that quietly suppresses enquiries, engagement and search performance.`,

`## Connect SEO, AEO and human usefulness

SEO helps a page become discoverable in search; answer engine optimisation helps its information become understandable and referenceable in generated answers. Both depend on useful, indexable content and credible signals. Establish clean crawling, canonical URLs, descriptive metadata and internal links first. Then answer the questions that influence real decisions, using concise definitions, well-labelled comparisons and first-hand detail. Structured data can clarify visible entities and relationships, but it cannot substitute for substance. Cite primary sources when facts require external support, identify the responsible author or organisation and update material when conditions change. Track visibility, citations and referral traffic where available, but connect them to branded demand, qualified enquiries and assisted sales rather than treating mentions as the final objective.`,

`## Create a purposeful internal linking system

Internal links should explain relationships, not merely distribute authority. Connect an educational article to the service that solves the next-stage problem, a service page to relevant proof, and a case study to the method it demonstrates. Use descriptive anchor text so the destination is clear before a click. Build topic hubs around important commercial themes, then audit them for missing links and isolated pages. Avoid placing dozens of generic links in every footer or repeating the same promotional block without context. A useful link answers the reader’s next likely question. Review internal links when pages are consolidated or URLs change, and include them in the editorial checklist for new content. A deliberate network helps people explore confidently and gives search systems stronger signals about which pages are central to each subject.`,

`## Plan conversion as a quality system

Conversion is not simply a form submission. Define what a qualified action looks like for the business and what information a prospect needs before taking it. Give each page one primary next step that matches its intent: explore a service, use a tool, request an audit or start a conversation. Explain what happens after the click, how long a response normally takes and what information will be useful. Keep forms proportionate to the commitment and test every confirmation state. Measure completion rate alongside lead quality, sales progression and source. A higher volume of unsuitable enquiries is not necessarily an improvement. Review recordings, abandonment and sales feedback to identify the uncertainty blocking action, then form a specific hypothesis and change the smallest meaningful part of the journey.`,

`## Measure a baseline before changing the system

Without a baseline, teams can mistake normal fluctuation for impact. Record the current state of organic landing pages, priority queries, qualified enquiries, conversion paths, page speed, publishing effort and sales feedback. Choose a small scorecard connected to the project’s purpose. Separate leading indicators, such as crawl coverage and engagement with proof, from business outcomes, such as qualified conversations and revenue contribution. Annotate launches, campaigns and major external events so comparisons retain context. Use consistent periods and segment branded from non-branded discovery where possible. Reporting should lead to a decision: continue, investigate, improve or stop. A dashboard full of numbers is not insight unless ownership, thresholds and next actions are clear.`,

`## Build an editorial evidence standard

Create a simple standard for what must be true before an article is published. Define acceptable sources, how claims are checked, when examples need approval, who owns review and what triggers an update. Distinguish observed results from assumptions and representative scenarios. Add meaningful publication and review dates rather than changing timestamps without changing substance. Preserve source notes even when they do not all appear on the page. For experience-led topics, interview the person closest to the work and capture specific decisions, constraints and lessons. For externally verifiable facts, prefer original research, official documentation and primary data. This discipline produces content that sales teams can confidently share and answer systems can more easily assess. It also protects the brand from the slow erosion caused by generic or unsupported publishing.`,

`## Turn one strong idea into a connected content system

Begin with a substantial source asset that resolves an important customer question. From it, create focused supporting pieces for social channels, email, sales enablement and related website pages. Each derivative should be adapted to its context rather than copied mechanically. A social post may surface one tension and invite discussion; a sales note may summarise the framework; a service page may use the insight to explain method. Link useful public derivatives back to the most complete owned source. Capture responses and objections as research for the next article. This approach makes consistency possible without demanding a new idea every day. It also keeps the website as the durable source of truth while social platforms perform their proper role: distribution, conversation and discovery.`,

`## Create a realistic ninety-day implementation plan

In the first thirty days, confirm goals, gather evidence, map audiences and audit the current experience. Fix urgent technical or clarity failures before adding volume. During days thirty-one to sixty, build or improve the highest-value pages, connect proof, establish measurement and create the supporting content brief. During days sixty-one to ninety, publish the first connected topic set, distribute it deliberately, review real behaviour and refine the weakest point in the journey. Assign one accountable owner to every decision and set approval dates before production begins. Keep a visible backlog for valuable ideas that are outside the current priority. A focused quarter should produce a working system and reliable learning, not a large collection of unfinished assets.`,

`## Use a pre-publication quality review

Before launch, ask whether the page has one clear purpose, an identifiable audience and a next step that matches intent. Confirm the title, summary and opening answer accurately describe the content. Check heading order, factual support, image rights, alternative text, mobile layout, keyboard access, forms, analytics, canonical URL, index directives and structured data. Test links and redirects in the environment that will actually go live. Read the page aloud to expose jargon and repetition. Ask someone outside the project to explain what the page offers and what they would do next. Record the owner and review date. This checklist should be short enough to use every time; deeper specialist checks can sit in linked launch procedures.`,

`## Know when specialist support becomes valuable

An internal team can make significant progress when the offer is stable, evidence is available and ownership is clear. Specialist support becomes valuable when positioning is contested, several audiences need different journeys, a migration puts existing search equity at risk, technical systems must be integrated or the team lacks capacity to maintain quality. A good partner should explain trade-offs and make decisions visible, not create dependency through mystery. Ask potential partners how they research, how they protect existing performance, what evidence they require, which work is included and how ownership transfers after launch. Compare proposals by scope and long-term operating cost, not only the initial number. The right engagement should improve both the public experience and the organisation’s ability to manage it.`,
];

const categoryNotes: Record<Article["section"], string> = {
  "Website Development": "For website development, translate these principles into page templates, component rules, content ownership, performance budgets, acceptance criteria and a migration plan. Design and engineering should work from the same audience journey so visual quality, technical quality and commercial clarity reinforce one another.",
  "SEO & AEO": "For SEO and AEO, prioritise indexable answers, clean topic relationships, original expertise and claims that can be verified. Technical foundations create access; strong information creates relevance; evidence creates confidence. Treat rankings and citations as routes to a useful business outcome, not isolated trophies.",
  "Content & Social Media": "For content and social media, protect the distinctive source idea. Capture real experience, adapt it to each channel and return the audience to a useful owned destination. Sustainable cadence follows a reliable extraction and approval system, not pressure to publish for its own sake.",
  "Marketing Strategy": "For marketing strategy, keep the chain from business objective to audience insight, message, channel, proof and measurement visible. If an activity cannot be connected to a decision or learning goal, question whether it belongs in the plan. Focus is a commercial advantage.",
};

export function getEditorialExpansion(article: Article) {
  const offset = article.slug.split("").reduce((total, character) => total + character.charCodeAt(0), 0) % chapters.length;
  const ordered = [...chapters.slice(offset), ...chapters.slice(0, offset)];
  return `\n\n## The detailed implementation playbook for ${article.title.toLowerCase()}\n\n${categoryNotes[article.section]} The following framework turns the core idea into a complete working method. Adapt the detail to your market, evidence, customer journey and operational constraints.\n\nUse this playbook as a decision tool rather than a rigid sequence. A smaller business may combine several responsibilities in one person, while a larger organisation may need separate owners for research, content, design, engineering, approval and measurement. In either case, write down the assumptions being made, the evidence that supports them and the point at which the team will review the decision. That record prevents the project from drifting when stakeholders change or new requests appear. It also makes later improvement faster because the team can compare what it expected with what customers actually did. Prioritise the parts that remove the greatest uncertainty for the audience and the greatest operational constraint for the business.\n\n${ordered.join("\n\n")}\n\n## Bringing the work back to the business\n\nThe purpose of ${article.title.toLowerCase()} is not to create another isolated marketing asset. It is to improve how the business is discovered, understood, trusted and chosen. Begin with the smallest high-value journey, establish a baseline and make responsibilities explicit. Publish when the work is useful and credible, then improve it with evidence from customers, search behaviour and sales outcomes. Keep the original question visible throughout the project so attractive execution never replaces commercial purpose. When the team can explain the audience, decision, proof, next step and measurement in plain language, it has a foundation that can grow without becoming confused.\n`;
}
